#pragma once

#define TAPPING_TERM 250
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD_PER_KEY

#define COMBO_TERM 60
#define COMBO_TERM_PER_COMBO
#define COMBO_VARIABLE_LEN
#define COMBO_MUST_HOLD_PER_COMBO

#define MOUSEKEY_DELAY          0
#define MOUSEKEY_INTERVAL       16
#define MOUSEKEY_WHEEL_DELAY    0
#define MOUSEKEY_MAX_SPEED      6
#define MOUSEKEY_TIME_TO_MAX    64
